export interface Activity {
  id: string;
  name: string;
  description: string;
  imageUrl: string;
  lat: number;
  lng: number;
  ageMin: number;
  ageMax: number;
  interests: string[];
  duration: "30-90min" | "halfDay" | "fullDay";
  priceBand: "free" | "$" | "$$" | "$$$";
  isIndoor: boolean;
  locationName: string;
  bookingUrl?: string | null;
  tags: string[];
}

export const seedActivities: Activity[] = [
  {
    id: "hk_001",
    name: "Star Ferry Across Harbour",
    description: "Enjoy a scenic cross-harbour ferry ride between Central and Tsim Sha Tsui on Hong Kong's iconic green and white ferry.",
    imageUrl: "/activities/star-ferry.jpg",
    lat: 22.2836,
    lng: 114.1526,
    ageMin: 3,
    ageMax: 10,
    interests: ["vehicles", "water"],
    duration: "30-90min",
    priceBand: "free",
    isIndoor: false,
    locationName: "Central Pier",
    tags: ["harbour", "iconic", "public-transport"],
  },
  {
    id: "hk_002",
    name: "Hong Kong Park Playground",
    description: "A beautiful park with modern playground equipment, waterfalls, and an aviary in the heart of the city.",
    imageUrl: "/activities/hk-park.jpg",
    lat: 22.2783,
    lng: 114.1623,
    ageMin: 2,
    ageMax: 8,
    interests: ["outdoor", "sports"],
    duration: "halfDay",
    priceBand: "free",
    isIndoor: false,
    locationName: "Admiralty, Hong Kong Park",
    tags: ["playground", "nature", "free"],
  },
  {
    id: "hk_003",
    name: "Creative Kids Messy Masters",
    description: "Let your little ones unleash their creativity with finger painting, splatter art, and sensory play sessions.",
    imageUrl: "/activities/art-studio.jpg",
    lat: 22.2821,
    lng: 114.1517,
    ageMin: 3,
    ageMax: 6,
    interests: ["art"],
    duration: "30-90min",
    priceBand: "$",
    isIndoor: true,
    locationName: "Sheung Wan",
    tags: ["art", "creative", "indoor"],
  },
  {
    id: "hk_004",
    name: "Island Pacific Hotel Pool",
    description: "A family-friendly outdoor swimming pool with shallow areas for toddlers and pool toys available.",
    imageUrl: "/activities/pool.jpg",
    lat: 22.2839,
    lng: 114.1264,
    ageMin: 2,
    ageMax: 10,
    interests: ["water"],
    duration: "halfDay",
    priceBand: "$$",
    isIndoor: false,
    locationName: "Sai Ying Pun",
    tags: ["swimming", "water", "summer"],
  },
  {
    id: "hk_005",
    name: "Tai Kwun Family Tour",
    description: "Explore Hong Kong's former police headquarters turned cultural center with family-friendly art installations.",
    imageUrl: "/activities/tai-kwun.jpg",
    lat: 22.2814,
    lng: 114.1542,
    ageMin: 4,
    ageMax: 12,
    interests: ["art", "history"],
    duration: "30-90min",
    priceBand: "free",
    isIndoor: true,
    locationName: "Central, Tai Kwun",
    tags: ["culture", "heritage", "art"],
  },
  {
    id: "hk_006",
    name: "Bowen Road Ball Games",
    description: "A traffic-free elevated walkway perfect for cycling, scootering, and ball games with harbour views.",
    imageUrl: "/activities/bowen-road.jpg",
    lat: 22.2789,
    lng: 114.1723,
    ageMin: 3,
    ageMax: 8,
    interests: ["sports", "outdoor"],
    duration: "halfDay",
    priceBand: "free",
    isIndoor: false,
    locationName: "Mid-Levels, Bowen Road",
    tags: ["sports", "active", "outdoor"],
  },
  {
    id: "hk_007",
    name: "Magnetic Tile Workshop",
    description: "Build 3D structures with colorful magnetic tiles in this hands-on STEM play session for young engineers.",
    imageUrl: "/activities/magnetic-tiles.jpg",
    lat: 22.2845,
    lng: 114.1520,
    ageMin: 4,
    ageMax: 8,
    interests: ["stem", "art"],
    duration: "30-90min",
    priceBand: "$",
    isIndoor: true,
    locationName: "Wan Chai",
    tags: ["stem", "building", "indoor"],
  },
  {
    id: "hk_008",
    name: "Central Library Storytime",
    description: "Free weekly storytime sessions at the stunning modern Central Library with interactive storytelling.",
    imageUrl: "/activities/library.jpg",
    lat: 22.2797,
    lng: 114.1614,
    ageMin: 2,
    ageMax: 6,
    interests: ["quiet"],
    duration: "30-90min",
    priceBand: "free",
    isIndoor: true,
    locationName: "Causeway Bay",
    tags: ["reading", "quiet", "free"],
  },
  {
    id: "hk_009",
    name: "Peak Tram Ride",
    description: "Ride the historic funicular railway up Victoria Peak for breathtaking views of the harbour and skyline.",
    imageUrl: "/activities/peak-tram.jpg",
    lat: 22.2713,
    lng: 114.1497,
    ageMin: 3,
    ageMax: 12,
    interests: ["vehicles", "outdoor"],
    duration: "30-90min",
    priceBand: "$",
    isIndoor: false,
    locationName: "Central, Garden Road",
    tags: ["tram", "views", "iconic"],
  },
  {
    id: "hk_010",
    name: "Kennedy Town Public Pool",
    description: "A modern public swimming complex with indoor and outdoor pools, perfect for family swim time.",
    imageUrl: "/activities/pool.jpg",
    lat: 22.2812,
    lng: 114.1268,
    ageMin: 2,
    ageMax: 10,
    interests: ["water", "sports"],
    duration: "halfDay",
    priceBand: "$",
    isIndoor: false,
    locationName: "Kennedy Town",
    tags: ["swimming", "sports", "water"],
  },
  {
    id: "hk_011",
    name: "Bounce Trampoline Park",
    description: "An indoor trampoline park with foam pits, dodgeball courts, and dedicated toddler jumping zones.",
    imageUrl: "/activities/trampoline.jpg",
    lat: 22.3125,
    lng: 114.2230,
    ageMin: 3,
    ageMax: 12,
    interests: ["sports", "outdoor"],
    duration: "halfDay",
    priceBand: "$$",
    isIndoor: true,
    locationName: "Quarry Bay",
    tags: ["active", "jumping", "indoor"],
  },
  {
    id: "hk_012",
    name: "Kowloon Park Flamingo Pond",
    description: "Watch pink flamingos and explore the bird park at this urban oasis in Tsim Sha Tsui.",
    imageUrl: "/activities/flamingos.jpg",
    lat: 22.2995,
    lng: 114.1690,
    ageMin: 2,
    ageMax: 10,
    interests: ["outdoor", "water"],
    duration: "30-90min",
    priceBand: "free",
    isIndoor: false,
    locationName: "Tsim Sha Tsui",
    tags: ["animals", "nature", "free"],
  },
];

export const interestOptions = [
  { id: "art", label: "Art", icon: "Palette", color: "#E86A33" },
  { id: "vehicles", label: "Vehicles", icon: "Car", color: "#4A7C59" },
  { id: "water", label: "Water", icon: "Waves", color: "#4A90D9" },
  { id: "sports", label: "Sports", icon: "Dumbbell", color: "#D4A843" },
  { id: "outdoor", label: "Outdoor", icon: "TreePine", color: "#5B9A5B" },
  { id: "quiet", label: "Quiet", icon: "BookOpen", color: "#8B7E74" },
  { id: "stem", label: "STEM", icon: "FlaskConical", color: "#8B5CF6" },
  { id: "history", label: "History", icon: "Landmark", color: "#B8860B" },
];

export const durationLabels: Record<string, string> = {
  "30-90min": "30-90 min",
  "halfDay": "Half day",
  "fullDay": "Full day",
};

export const priceLabels: Record<string, string> = {
  "free": "Free",
  "$": "Budget",
  "$$": "Moderate",
  "$$$": "Premium",
};
