import { getDb } from "../api/queries/connection";
import { activities } from "./schema";

const activitySeedData = [
  {
    id: "hk_001",
    name: "Star Ferry Across Harbour",
    description: "Enjoy a scenic cross-harbour ferry ride between Central and Tsim Sha Tsui on Hong Kong's iconic green and white ferry.",
    imageUrl: "/activities/star-ferry.jpg",
    lat: "22.2836",
    lng: "114.1526",
    ageMin: 3,
    ageMax: 10,
    interests: JSON.stringify(["vehicles", "water"]),
    duration: "30-90min" as const,
    priceBand: "free" as const,
    isIndoor: false,
    locationName: "Central Pier",
    bookingUrl: null,
    tags: JSON.stringify(["harbour", "iconic", "public-transport"]),
  },
  {
    id: "hk_002",
    name: "Hong Kong Park Playground",
    description: "A beautiful park with modern playground equipment, waterfalls, and an aviary in the heart of the city.",
    imageUrl: "/activities/hk-park.jpg",
    lat: "22.2783",
    lng: "114.1623",
    ageMin: 2,
    ageMax: 8,
    interests: JSON.stringify(["outdoor", "sports"]),
    duration: "halfDay" as const,
    priceBand: "free" as const,
    isIndoor: false,
    locationName: "Admiralty, Hong Kong Park",
    bookingUrl: null,
    tags: JSON.stringify(["playground", "nature", "free"]),
  },
  {
    id: "hk_003",
    name: "Creative Kids Messy Masters",
    description: "Let your little ones unleash their creativity with finger painting, splatter art, and sensory play sessions.",
    imageUrl: "/activities/art-studio.jpg",
    lat: "22.2821",
    lng: "114.1517",
    ageMin: 3,
    ageMax: 6,
    interests: JSON.stringify(["art"]),
    duration: "30-90min" as const,
    priceBand: "$" as const,
    isIndoor: true,
    locationName: "Sheung Wan",
    bookingUrl: null,
    tags: JSON.stringify(["art", "creative", "indoor"]),
  },
  {
    id: "hk_004",
    name: "Island Pacific Hotel Pool",
    description: "A family-friendly outdoor swimming pool with shallow areas for toddlers and pool toys available.",
    imageUrl: "/activities/pool.jpg",
    lat: "22.2839",
    lng: "114.1264",
    ageMin: 2,
    ageMax: 10,
    interests: JSON.stringify(["water"]),
    duration: "halfDay" as const,
    priceBand: "$$" as const,
    isIndoor: false,
    locationName: "Sai Ying Pun",
    bookingUrl: null,
    tags: JSON.stringify(["swimming", "water", "summer"]),
  },
  {
    id: "hk_005",
    name: "Tai Kwun Family Tour",
    description: "Explore Hong Kong's former police headquarters turned cultural center with family-friendly art installations.",
    imageUrl: "/activities/tai-kwun.jpg",
    lat: "22.2814",
    lng: "114.1542",
    ageMin: 4,
    ageMax: 12,
    interests: JSON.stringify(["art", "history"]),
    duration: "30-90min" as const,
    priceBand: "free" as const,
    isIndoor: true,
    locationName: "Central, Tai Kwun",
    bookingUrl: null,
    tags: JSON.stringify(["culture", "heritage", "art"]),
  },
  {
    id: "hk_006",
    name: "Bowen Road Ball Games",
    description: "A traffic-free elevated walkway perfect for cycling, scootering, and ball games with harbour views.",
    imageUrl: "/activities/bowen-road.jpg",
    lat: "22.2789",
    lng: "114.1723",
    ageMin: 3,
    ageMax: 8,
    interests: JSON.stringify(["sports", "outdoor"]),
    duration: "halfDay" as const,
    priceBand: "free" as const,
    isIndoor: false,
    locationName: "Mid-Levels, Bowen Road",
    bookingUrl: null,
    tags: JSON.stringify(["sports", "active", "outdoor"]),
  },
  {
    id: "hk_007",
    name: "Magnetic Tile Workshop",
    description: "Build 3D structures with colorful magnetic tiles in this hands-on STEM play session for young engineers.",
    imageUrl: "/activities/magnetic-tiles.jpg",
    lat: "22.2845",
    lng: "114.1520",
    ageMin: 4,
    ageMax: 8,
    interests: JSON.stringify(["stem", "art"]),
    duration: "30-90min" as const,
    priceBand: "$" as const,
    isIndoor: true,
    locationName: "Wan Chai",
    bookingUrl: null,
    tags: JSON.stringify(["stem", "building", "indoor"]),
  },
  {
    id: "hk_008",
    name: "Central Library Storytime",
    description: "Free weekly storytime sessions at the stunning modern Central Library with interactive storytelling.",
    imageUrl: "/activities/library.jpg",
    lat: "22.2797",
    lng: "114.1614",
    ageMin: 2,
    ageMax: 6,
    interests: JSON.stringify(["quiet"]),
    duration: "30-90min" as const,
    priceBand: "free" as const,
    isIndoor: true,
    locationName: "Causeway Bay",
    bookingUrl: null,
    tags: JSON.stringify(["reading", "quiet", "free"]),
  },
  {
    id: "hk_009",
    name: "Peak Tram Ride",
    description: "Ride the historic funicular railway up Victoria Peak for breathtaking views of the harbour and skyline.",
    imageUrl: "/activities/peak-tram.jpg",
    lat: "22.2713",
    lng: "114.1497",
    ageMin: 3,
    ageMax: 12,
    interests: JSON.stringify(["vehicles", "outdoor"]),
    duration: "30-90min" as const,
    priceBand: "$" as const,
    isIndoor: false,
    locationName: "Central, Garden Road",
    bookingUrl: null,
    tags: JSON.stringify(["tram", "views", "iconic"]),
  },
  {
    id: "hk_010",
    name: "Kennedy Town Public Pool",
    description: "A modern public swimming complex with indoor and outdoor pools, perfect for family swim time.",
    imageUrl: "/activities/pool.jpg",
    lat: "22.2812",
    lng: "114.1268",
    ageMin: 2,
    ageMax: 10,
    interests: JSON.stringify(["water", "sports"]),
    duration: "halfDay" as const,
    priceBand: "$" as const,
    isIndoor: false,
    locationName: "Kennedy Town",
    bookingUrl: null,
    tags: JSON.stringify(["swimming", "sports", "water"]),
  },
  {
    id: "hk_011",
    name: "Bounce Trampoline Park",
    description: "An indoor trampoline park with foam pits, dodgeball courts, and dedicated toddler jumping zones.",
    imageUrl: "/activities/trampoline.jpg",
    lat: "22.3125",
    lng: "114.2230",
    ageMin: 3,
    ageMax: 12,
    interests: JSON.stringify(["sports", "outdoor"]),
    duration: "halfDay" as const,
    priceBand: "$$" as const,
    isIndoor: true,
    locationName: "Quarry Bay",
    bookingUrl: null,
    tags: JSON.stringify(["active", "jumping", "indoor"]),
  },
  {
    id: "hk_012",
    name: "Kowloon Park Flamingo Pond",
    description: "Watch pink flamingos and explore the bird park at this urban oasis in Tsim Sha Tsui.",
    imageUrl: "/activities/flamingos.jpg",
    lat: "22.2995",
    lng: "114.1690",
    ageMin: 2,
    ageMax: 10,
    interests: JSON.stringify(["outdoor", "water"]),
    duration: "30-90min" as const,
    priceBand: "free" as const,
    isIndoor: false,
    locationName: "Tsim Sha Tsui",
    bookingUrl: null,
    tags: JSON.stringify(["animals", "nature", "free"]),
  },
];

async function seed() {
  const db = getDb();
  
  console.log("Seeding activities...");
  
  for (const activity of activitySeedData) {
    await db.insert(activities).values(activity).onDuplicateKeyUpdate({
      set: {
        name: activity.name,
        description: activity.description,
        imageUrl: activity.imageUrl,
        lat: activity.lat,
        lng: activity.lng,
        ageMin: activity.ageMin,
        ageMax: activity.ageMax,
        interests: activity.interests,
        duration: activity.duration,
        priceBand: activity.priceBand,
        isIndoor: activity.isIndoor,
        locationName: activity.locationName,
        bookingUrl: activity.bookingUrl,
        tags: activity.tags,
      },
    });
  }
  
  console.log(`Seeded ${activitySeedData.length} activities`);
}

seed().catch(console.error);
